apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-vrecli
  namespace: utility
  labels:
    app: bff-vrecli
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-vrecli
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: bff-vrecli
    spec:
      containers:
        - name: bff-vrecli
          image: registry-gitlab.indocresearch.org/charite/bff_vrecli:<VERSION>
          ports:
            - containerPort: 5080
          env:
          - name: env
            value: "dev"
          - name: CONFIG_CENTER_ENABLED
            value: "true"
          - name: CONFIG_CENTER_BASE_URL
            value: "http://common.utility:5062/"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: bff-vrecli
  namespace: utility
  labels:
    app: bff-vrecli
spec:
  ports:
  - name: http
    port: 5080
    targetPort: 5080
  selector:
    app: bff-vrecli
  type: LoadBalancer
